### ISSUE TITLE
在多台机器上均出现该问题

### ISSUE THREAD

**Issue by Lenovo0003yf** [Misaka-blog/XrayR#35]
**描述该错误**
简单地描述一下这个bug是什么

**复现**
复现该bug的步骤

**环境和版本**
 - 系统 Ubuntu 20.04
 - 架构 AMD64
 - 面板 sspanel
 - 协议 vmess
 - 版本 0.8.2.6
 - 部署方式 一键脚本

**日志和错误**
Jun 18 21:08:01 VM-8-4-ubuntu systemd[1]: Started XrayR Service.
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]: XrayR 0.8.2.6 (A Xray backend that supports many panels)
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]: 2022/06/18 21:08:01 Start the panel..
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]: 2022/06/18 21:08:01 Xray Core Version: 1.5.5
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1961c69]
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]: goroutine 1 [running]:
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]: github.com/Misaka-blog/XrayR/panel.(*Panel).Start(0xc00008f900)
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]:         github.com/Misaka-blog/XrayR/panel/panel.go:165 +0x1c9
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]: main.main()
Jun 18 21:08:01 VM-8-4-ubuntu XrayR[695818]:         github.com/Misaka-blog/XrayR/main/main.go:92 +0x1ed
Jun 18 21:08:01 VM-8-4-ubuntu systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 18 21:08:01 VM-8-4-ubuntu systemd[1]: XrayR.service: Failed with result 'exit-code'.

**额外的内容**
配置文件已配置好

**Comment by crossfw** [comment]
@Lenovo0003yf 程序没有获得正确的服务器应答。一般是由于CDN阻挡了程序通信，请根据ip或其他方式放行
